title: Taura Laboratory
description: ""
url: https://www.eidos.ic.i.u-tokyo.ac.jpbu
remote_theme: just-the-docs/just-the-docs
favicon_ico: "/assets/images/favicon.png"
plugins:
  - jemoji
  - jekyll-redirect-from
math: mathjax
